serviceAccount: hemanth-861@project-2-458822.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/admin-app'
    - '-f'
    - 'web-apps-deployment/web-apps-deployment/admin-app/Dockerfile'
    - 'web-apps-deployment/web-apps-deployment/admin-app'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'admin-app'  # 🔧 Corrected: Was incorrectly written as 'user-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/admin-app'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--clear-vpc-connector'  # ✅ This disables VPC usage during deploy
