serviceAccount: projects/project-2-458822/serviceAccounts/hemanth-861@project-2-458822.iam.gserviceaccount.com


options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/admin-app'
    - '-f'
    - 'web-apps-deployment/web-apps-deployment/admin-app/cloudbuild.yaml  
    - 'web-apps-deployment/web-apps-deployment/admin-app/Dockerfile 
    - 'web-apps-deployment/web-apps-deployment/admin-app'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'admin-app'  # ✅ Make sure this matches the service you want
    - '--image'
    - 'gcr.io/$PROJECT_ID/admin-app'
    - '--region'
    - 'us-central1'
    - '--platform'
    - '
