options:
  logging: CLOUD_LOGGING_ONLY
  # Or if you want a logs bucket instead:
  # logsBucket: gs://your-logs-bucket-name

serviceAccount: your-build-service-account@project.iam.gserviceaccount.com

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/user-app', '.']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'user-app'
  - '--image'
  - 'gcr.io/$PROJECT_ID/user-app'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
