steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/user-app', '.']
    dir: 'web-apps-deployment/end-user-app'  # 👈 IMPORTANT: adjust if your Dockerfile lives elsewhere

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'user-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/user-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/user-app'

options:
  logging: CLOUD_LOGGING_ONLY
